/**
 * flirtyLinesVulgar.js — Phrases taquines, drôles et un peu vulgaires
 * Ton : chambreur, complice, affectueux, second degré
 * ⚠️ Jamais insultant, jamais sexuel explicite, toujours drôle
 */

export const flirtyLinesVulgar = {

  // ━━━ Accueil ━━━
  welcome: [
    "Bon… j'ai codé tout ça juste pour toi, alors fais pas ta relou.",
    "Bienvenue. Oui c'est romantique. Oui j'assume.",
    "Attention, site dangereusement mignon.",
    "Respire. C'est que de l'amour et un peu de vice.",
    "T'es prête ? Parce que moi j'ai mis mon cœur dans ce code, bordel.",
    "Ce site est officiellement plus romantique que moi IRL.",
    "Bienvenue dans le truc le plus niais que j'ai jamais fait. Et j'en suis fier.",
    "Si t'es pas émue à la fin, je rembourse. Non j'déconne.",
    "Ok, installe-toi bien. Ça va être mignon. Putain de mignon.",
    "J'ai passé des heures là-dessus. T'as intérêt à sourire.",
    "Prépare tes zygomatiques, ça va piquer.",
    "Allez entre, fais comme chez toi. C'est un peu chez toi de toute façon.",
    "J'aurais pu t'offrir des fleurs. J'ai codé un site. Deal with it.",
    "Ce site a plus de love que toute la discographie de Francis Cabrel.",
    "Spoiler : tu vas kiffer. Ou au minimum sourire.",
    "Si ce site était un plat, ce serait un fondant au chocolat. Dégoulinant d'amour.",
    "Bienvenue dans mon délire romantique. Aucune issue de secours.",
    "T'inquiète, c'est safe. Juste de l'amour et du code un peu bancal.",
    "Entre, y'a de la place. Et du wifi. Et de l'amour.",
    "Tu vas voir, c'est comme moi : un peu con, mais attachant.",
    "Clique et profite. Comme dans la vie. Mais en plus cute.",
    "J'espère que t'as du temps devant toi. Parce que ça va être long… de bonheur.",
    "Mise en garde : risque élevé de sourire niais.",
    "Bienvenue sur le site le plus simp d'internet. Et fier de l'être.",
    "C'est parti. Attache ta ceinture, bébé. 💖",
    "On m'a dit que coder un site pour sa meuf c'était overkill. Ils ont tort.",
  ],

  // ━━━ Bouton NON qui fuit ━━━
  dodgeNo: [
    "Arrête d'essayer, ce bouton est plus lâche que moi.",
    "PUTAIN MAIS CLIQUE PAS LÀ.",
    "Il court parce qu'il sait.",
    "Même le bouton dit non à ton non.",
    "Ce NON est en PLS.",
    "Tu crois quoi ? Que j'ai pas prévu le coup ?",
    "Le bouton : 'Nope nope nope.' 🏃",
    "T'es têtue bordel. Mais moi aussi.",
    "Ce bouton a plus de cardio que toi.",
    "Il esquive mieux que Mbappé ce truc.",
    "NON. Le bouton a dit NON à ton NON.",
    "Tu perds ton temps. Comme quand tu cherches la télécommande.",
    "Ah ah ah. Tu pensais que ça marcherait ?",
    "Le bouton est en mode survie. Laisse-le tranquille.",
    "Il est parti en courant. Comme mes ex. Non j'déconne t'es la seule.",
    "Ce bouton a un meilleur instinct de survie que moi.",
    "Chaque tentative le rend plus fort. Comme moi pour toi, femme. Cheesy hein ?",
    "Merde, t'insistes vraiment.",
    "Ok ok ok, respire. Le OUI est juste là. JUSTE. LÀ.",
    "Le NON est en burn-out à force de fuir.",
    "Ce bouton a un avocat. Il refuse d'être cliqué.",
    "T'as un problème avec le mot OUI ou quoi ?",
    "Le bouton NON : 'J'ai pas signé pour ça.'",
    "Putain mais lâche ce bouton, il a une famille.",
    "À ce stade, le bouton NON dépose une main courante.",
    "Tu sais que tu peux juste cliquer sur OUI hein ? Genre, facilement ?",
    "Le bouton fait du parkour pour t'éviter. Respect.",
  ],

  // ━━━ Le OUI grandit ━━━
  yesGrow: [
    "Regarde-le prendre confiance… comme moi.",
    "Il gonfle. Comme mon ego.",
    "Plus tu forces, plus il devient énorme.",
    "Ce bouton a clairement faim d'amour.",
    "Le OUI en mode bodybuilding.",
    "Il grandit. Il prend de la place. Comme mes sentiments.",
    "Le OUI : 'C'est MON moment.'",
    "Plus gros. PLUS GROS. Voilà comme ça.",
    "Ce bouton a mangé du lion.",
    "Le OUI fait sa crise d'ado, il veut être vu.",
    "Ça pousse bien. Comme notre amour. 🌱",
    "Le OUI prend ses aises. Comme moi dans le lit.",
    "Il est en train de devenir IMMENSE. Un peu comme moi pour toi, femme.",
    "Si tu cliques pas bientôt, il va envahir l'écran.",
    "Le OUI fait du cardio là. Il grossit à vue d'œil.",
    "Bientôt il sera plus gros que l'écran. Et ce sera ta faute.",
    "Le OUI a pris 3 tailles. Comme moi après les fêtes.",
    "Tu vois ? C'est la bonne réponse. Le bouton le sait.",
    "Le OUI : 'Regardez-moi. REGARDEZ-MOI.' 👀",
    "Il gonfle d'espoir. Ne le déçois pas.",
    "Bordel, il est ÉNORME maintenant.",
    "Le OUI est en pleine croissance. Fais pas le/la timide.",
    "Regarde, même le code veut que tu dises oui.",
    "Le bouton OUI fait des pompes en attendant ton clic.",
    "Plus tu esquives, plus il devient impossible à ignorer.",
    "Ce bouton a plus de présence que moi en soirée.",
  ],

  // ━━━ Clic sur OUI ━━━
  yesClicked: [
    "PUTAIN ENFIN.",
    "Bon choix. Très bon choix.",
    "Voilà. C'était pas si dur, bordel.",
    "Le site te juge pas. Moi si. (positivement)",
    "OUI VALIDÉ PAR LE CONSEIL DU LOVE.",
    "C'est officiel. T'as dit oui. Pas de retour en arrière.",
    "MERCI. Mon cœur en avait marre d'attendre.",
    "Le bouton est en larmes de joie.",
    "Enfin ! J'ai cru que t'allais jamais cliquer.",
    "OUI ! Le destin a parlé (et le code aussi).",
    "GG. T'as débloqué le niveau suivant : l'amour infini.",
    "Le OUI est validé. Comme nous. 💖",
    "C'était la bonne décision. La seule, en fait.",
    "Bravo. Le bouton peut enfin se reposer.",
    "YESSSSS. Je suis plus heureux que ce bouton.",
    "Clic légendaire. 10/10. Sans appel.",
    "T'as fait le bon choix. Comme le jour où tu m'as choisi(e).",
    "Victoire. On peut passer aux choses sérieuses maintenant.",
    "OUI comptabilisé. Le love-o-mètre explose.",
    "Je le savais. Au fond t'es folle de moi.",
    "Ok, le doute est levé. T'es officiellement ma Valentine.",
    "Le plus beau clic de l'histoire d'internet.",
    "Enfin un peu de bon sens. Merci bordel.",
    "YES ! Mon cœur fait la ola.",
    "C'est enregistré. En 47 copies. Pas de retour possible. 😏",
    "OUI. Trois lettres. Un monde de bonheur.",
  ],

  // ━━━ Attrape-cœurs ━━━
  catchHearts: [
    "Attrape-les comme si ta vie sentimentale en dépendait.",
    "Plus vite. PLUS VITE.",
    "Ok là tu forces un peu… j'aime bien.",
    "C'est pas Tinder ici mais presque.",
    "Mais arrête de les rater, merde.",
    "T'as des doigts ou des saucisses ?",
    "CLIQUE PLUS VITE BORDEL.",
    "Chaque cœur attrapé = 1 bisou.",
    "Tu gères ! Enfin… pour l'instant.",
    "Continue comme ça, t'es une machine.",
    "Les cœurs s'envolent et toi tu galères. Mignon.",
    "C'est comme au début de notre relation : faut courir après.",
    "Allez allez allez, on lâche rien !",
    "Tu les attrapes comme tu m'as attrapé(e) le cœur. Avec difficulté.",
    "Oh un cœur ! Oh un autre ! Oh t'as raté.",
    "Si t'étais un Pokémon dresseur, tu serais… en galère.",
    "Putain, t'en as raté un ÉNORME.",
    "Trop lente. Ou trop rapide. Y'a pas de juste milieu avec toi.",
    "T'es à fond et j'adore ça.",
    "Les cœurs paniquent. Normal, t'es une prédatrice.",
    "Un cœur de perdu, dix de retrouvés. Ah non ça marche pas comme ça.",
    "Allez ma championne, montre-leur qui commande.",
    "C'est beau cet acharnement. Comme quand tu veux le dernier mot.",
    "ATTRAPE. CES. PUTAINS. DE. CŒURS.",
    "Chaque cœur raté me brise un peu. Dramatique ? Moi ? Jamais.",
    "Tu fais du tri sélectif ou tu attrapes tout ?",
  ],

  // ━━━ Quiz bonne réponse ━━━
  quizCorrect: [
    "Trop forte. Ça me fout presque le seum.",
    "Bon… t'as pas triché. Je crois.",
    "Validé. T'es officiellement incroyable.",
    "J'avais raison de t'aimer.",
    "GG. Cerveau + beauté = combo fatal.",
    "Bonne réponse ! T'es flippante en fait.",
    "Putain, tu me connais trop bien. C'est presque chelou.",
    "CORRECT. Mon cœur valide.",
    "T'as répondu trop vite. C'est suspect.",
    "Bonne réponse. Tu veux un cookie ? 🍪",
    "Impressionnant. Tu retiens tout ou quoi ?",
    "Sans faute. Comme toi dans ma vie. (Oui c'est cheesy, et alors ?)",
    "BOOM. Bonne réponse. T'es un génie.",
    "Tu me connais par cœur et ça me fait flipper.",
    "Validé sans hésitation. Le couple est solide.",
    "Bravo ! Je suis presque jaloux(se) de ton cerveau.",
    "Ça c'est la réponse d'une vraie. 💪",
    "Réponse parfaite. Personne parfaite. Coïncidence ? Non.",
    "T'enchaînes les bonnes réponses. Comme t'enchaînes les raisons de t'aimer.",
    "Ok, tu gères. Officiellement.",
    "C'est ça. EXACTEMENT ça. T'es trop forte.",
    "Bonne réponse. J'ai la meuf la plus intelligente du game.",
    "CORRECT ! Prends ton point et sois fière.",
    "Tu déchires. Moi je suis fier(ère).",
    "La science confirme : t'es incroyable.",
    "Bonne réponse. Le QI de notre couple vient de monter.",
  ],

  // ━━━ Quiz mauvaise réponse ━━━
  quizWrong: [
    "NON. Mais joli effort.",
    "Tu fais exprès ou quoi ?",
    "Bon… on va faire comme si j'avais rien vu.",
    "C'est faux. Mais je t'aime quand même, reloue.",
    "Raté. Comme mon cœur quand t'es pas là. Non ça veut rien dire.",
    "Euh… non. T'es sûre de toi là ?",
    "Faux. Mais t'es toujours cute quand tu te trompes.",
    "NON MAIS COMMENT ?!",
    "Ok. On oublie. On passe à autre chose. Vite.",
    "Mauvaise réponse. Je suis blessé(e). Pas vraiment. Un peu.",
    "T'inquiète, Einstein aussi se trompait. Je crois.",
    "Faux. Mais je t'aime trop pour t'en vouloir.",
    "C'est pas grave. C'est PRESQUE pas grave.",
    "Perdu. Comme mes espoirs pour cette question.",
    "Nope. Essaie encore. T'as le droit parce que t'es toi.",
    "Mauvaise réponse ! Mon cœur saigne. Métaphoriquement.",
    "Ah. Bah non. Mais ça reste adorable.",
    "Faux. On en parle ou on passe ? On passe.",
    "T'as choisi la pire réponse. Talent.",
    "Bon, c'est pas comme si je tenais les comptes. (Si.)",
    "Raté ! Mais tu restes la meilleure du monde.",
    "Noooon. C'était pas ça du tout.",
    "Merde. Tu connais pas cette réponse ? On vit ensemble non ?",
    "Faux. Mais hé, personne est parfait. Enfin si, moi. Non j'déconne.",
    "Mauvaise réponse mais au moins t'as essayé. C'est l'intention qui compte.",
    "OK on va mettre ça sur le compte de la fatigue.",
  ],

  // ━━━ Memory match ━━━
  memoryMatch: [
    "Encore une paire. T'es en feu.",
    "Putain mais t'es trop forte.",
    "Le cerveau est ON.",
    "Ça match mieux que nous au début.",
    "BOOM. Paire trouvée. T'es un monstre.",
    "Match parfait. Comme nous. Voilà c'est dit.",
    "T'as une mémoire d'éléphant ou quoi ?",
    "Paire validée ! Ton cerveau est chaud bouillant.",
    "GG. Encore une et t'es au top.",
    "T'enchaînes comme une pro. Je suis impressionné(e).",
    "Le memory tremble devant toi.",
    "PAIRE ! T'es en mode machine là.",
    "Mémoire de ouf. Tu retiens aussi quand j'ai tort hein ?",
    "Bravo ! C'est presque trop facile pour toi.",
    "Match ! Comme notre premier match. Nostalgique ? 😏",
    "T'as trouvé ! Mon cœur fait un backflip.",
    "Encore une paire. Le jeu va bientôt pleurer.",
    "Tu les retiens toutes ? C'est borderline flippant.",
    "VALIDÉ. T'es officiellement la reine du memory.",
    "Bien joué ! T'as aussi retenu notre anniversaire j'espère ?",
    "Paire trouvée. Ton cerveau est un coffre-fort.",
    "Ça match. Comme nous quand on se chambre.",
    "Deux de plus ! T'es inarrêtable.",
    "Le jeu peut rien contre toi.",
    "Match ! Quelqu'un peut l'arrêter ?",
    "Putain, t'as la mémoire de Sherlock.",
  ],

  // ━━━ Rage Mode (trop d'esquives sur NON) ━━━
  rageMode: [
    "Ok là tu cherches la merde.",
    "T'as signé pour l'amour, pas pour la violence.",
    "Je vais agrandir le OUI encore plus, fais pas chier.",
    "Le site commence à perdre patience.",
    "BORDEL DE MERDE, CLIQUE SUR OUI.",
    "Tu sais que t'as pas le choix hein ?",
    "Le bouton NON est en thérapie maintenant. Bravo.",
    "Ok. On va passer au plan B. Et le plan B c'est OUI.",
    "T'as dépassé la limite. Le love est OBLIGATOIRE.",
    "Le site va s'auto-détruire si tu continues.",
    "STOP. Juste… STOP. Et clique OUI.",
    "T'es en train de briser le cœur d'un développeur. Content(e) ?",
    "Le code est en PLS. Comme moi. Clique OUI bordel.",
    "On est à 2 doigts de la mutinerie digitale là.",
    "Tu testes mes limites. Le site aussi.",
    "OK. Le NON est officiellement annulé. Terminé. Fini.",
    "Pourquoi tu fais ça ? POURQUOI ?",
    "Le bouton NON vient de démissionner.",
    "Je vais remplir tout l'écran de OUI si tu continues.",
    "C'est un site d'amour, pas un ring de boxe.",
    "T'es relou mais je t'aime quand même. CLIQUE SUR OUI.",
    "Le serveur surchauffe à cause de ton entêtement.",
    "Alerte rouge. Niveau de OUI : CRITIQUE.",
    "Tu fais la difficile ? Moi aussi je peux être chiant(e).",
    "DERNIER AVERTISSEMENT. OUI. MAINTENANT.",
    "Le bouton NON a quitté le chat.",
  ],

  // ━━━ Reveal final ━━━
  finalReveal: [
    "Bon. Trêve de conneries.",
    "Je t'aime. Fort. Vraiment.",
    "Tout ça pour te dire un truc simple.",
    "T'es ma personne préférée. Voilà.",
    "J'ai gagné au jeu parce que je t'ai.",
    "Après tous ces jeux débiles… voilà le message.",
    "Putain que je t'aime.",
    "Bon. On arrête de déconner. C'est sérieux maintenant.",
    "T'es la meilleure chose qui me soit arrivée. Point.",
    "Je suis nul(le) en mots, mais pas en sentiments.",
    "Tout ce bordel, c'était juste pour te dire ça.",
    "T'es mon exception. Ma constante. Mon tout.",
    "Si l'amour était un code, t'en serais la variable principale.",
    "Derrière le sarcasme, y'a un cœur qui bat pour toi.",
    "Merde, j'ai les yeux qui brillent en écrivant ça.",
    "T'es pas parfaite. Moi non plus. Mais ensemble on l'est.",
    "Le plus beau bug de ma vie, c'est d'être tombé(e) sur toi.",
    "Tout ça pour trois mots. Je. T'aime.",
    "Ce site est con. Mais il est sincère. Comme moi.",
    "Voilà. C'est tout. C'est toi. C'est nous. ❤️",
    "T'es la raison pour laquelle je souris comme un con.",
    "Ce site avait un seul but : te faire sourire. Mission accomplie ?",
    "Je t'aime tellement que j'ai appris à coder. Enfin presque.",
    "Fin du délire. Début du vrai message.",
    "T'es ce qui m'est arrivé de mieux. Et je le pense.",
    "Joyeuse Saint-Valentin, à toi, ma préférée. 💖",
  ],
};

// ━━━ Phrase RARE (2-3% de chance) ━━━
export const RARE_LINE = "Ok là c'est officiellement le site le plus con que j'ai jamais codé. Mais pour toi. 💖";
export const RARE_CHANCE = 0.025; // 2.5%

// ━━━ Phrases soft (fallback) ━━━
export const flirtyLinesSoft = {
  welcome: [
    "Bienvenue mon cœur 💕",
    "Prête pour une surprise ?",
    "Ce site est rien que pour toi.",
    "Installe-toi confortablement… 🥰",
    "Quelqu'un t'aime très fort par ici.",
  ],
  dodgeNo: [
    "Ce bouton est timide 😜",
    "Essaie encore !",
    "Le destin a parlé…",
    "Hmm, mauvais choix !",
    "Ce bouton dit non à ton non !",
  ],
  yesGrow: [
    "Le OUI prend confiance 💪",
    "Il grandit comme notre amour…",
    "Regarde-le briller !",
    "De plus en plus gros !",
    "Le OUI est tout content !",
  ],
  yesClicked: [
    "Yeees ! 🎉",
    "Meilleur choix du monde !",
    "Mon cœur est comblé 💖",
    "Enfin ! Je suis si heureux(se) !",
    "C'était la bonne réponse !",
  ],
  catchHearts: [
    "Bravo, continue ! 💕",
    "T'es trop forte !",
    "Encore encore !",
    "Les cœurs t'adorent !",
    "Tu gères !",
  ],
  quizCorrect: [
    "Bonne réponse ! 🌟",
    "Tu me connais si bien !",
    "Impressionnant !",
    "Bravo mon cœur !",
    "Parfait !",
  ],
  quizWrong: [
    "Pas tout à fait… 😊",
    "Essaie encore !",
    "Presque !",
    "C'est pas grave !",
    "On apprend ensemble !",
  ],
  memoryMatch: [
    "Bien joué ! 🧠",
    "Quelle mémoire !",
    "Paire trouvée !",
    "Trop forte !",
    "Encore une !",
  ],
  rageMode: [
    "Allez, dis oui ! 🥺",
    "S'il te plaît…",
    "Le OUI attend…",
    "C'est la bonne réponse !",
    "Fais-moi plaisir 💕",
  ],
  finalReveal: [
    "Je t'aime 💖",
    "Tu es mon monde.",
    "Pour toujours.",
    "Mon cœur t'appartient.",
    "Joyeuse Saint-Valentin 💕",
  ],
};
